website: https://geogeeks.org
domain: geogeeks.org
title: Geogeeks Perth
email: geogeeks.perth@gmail.com
keep_files: [ workshops, geogeeks.ics ]
plugins:
    - jekyll-leaflet
timezone: Australia/Perth
